as yet unclassified
prepareCPPFile
	stream nextPutAll: '//stochastic model';cr.
	stream nextPutAll: '#include <iostream>';cr.
	stream nextPutAll: '#include <string>';cr.
	stream nextPutAll: '#include <stdio.h>';cr.
	stream nextPutAll: '#include <stdlib.h>';cr.
	stream nextPutAll: '#include <math.h>';cr.
	stream nextPutAll: '#include <time.h>';cr.
	stream nextPutAll: '#include <fstream>';cr.
	stream nextPutAll: '#include <sstream>';cr;cr.	
		
	stream nextPutAll: 'using namespace std;';cr;cr.

	
	
	


