"
This version 2 package of the Kendrick meta model implements a Continuous-time Markov Chain.

It contains the classes:
- `K2CTMC`, the class designating the Continuous-time Markov chain
- `K2CTMCState`, for states;
- `K2CTMCTransition`, for CTMC transitions;
- And finally a class `BlockClosure` allowing the definition of transition matrix.
"
Class {
	#name : #ManifestKendrick2CTMC,
	#superclass : #PackageManifest,
	#category : #'Kendrick2-CTMC-Manifest'
}
