as yet unclassified
expectedFailures

^{#testKEEquation. #testKEEquationWithIndexedVariable. #testKEBinaryExpressionWithOneCompartment. #testKEBinaryExpressionWithParentheses. #testKECompartmentNode. #testKEEquationWithFunctionSigmaInExpression. #testKEUnaryExpression. #testKEVariableNode. #testKEParameterAs2DArrayNode. #testKEParameterAs3DArrayNode. #testKEParameterAsArrayNode. #testKEParameterNode}