as yet unclassified
prepareCPPFile
	stream nextPutAll: '//individual based model';cr.
	stream nextPutAll: '#include <iostream>';cr.
	stream nextPutAll: '#include <string>';cr.
	stream nextPutAll: '#include <stdio.h>';cr.
	stream nextPutAll: '#include <stdlib.h>';cr.
	stream nextPutAll: '#include <math.h>';cr.
	stream nextPutAll: '#include <limits.h>';cr.
	
	stream nextPutAll: 'using namespace std;';cr.
	
	