
!RungeKuttaSolver class methodsFor: 'as yet unclassified'!
toto
"// Fourth order Runge-Kutta for a single ordinary differential equation (ODE)
    	// Static method
	    public static double fourthOrder(DerivFunction g, double x0, double y0, double xn, double h){

	        RungeKutta rk = new RungeKutta();
	        rk.setInitialValueOfX(x0);
	        rk.setFinalValueOfX(xn);
	        rk.setInitialValueOfY(y0);
	        rk.setStepSize(h);

	        return rk.fourthOrder(g);
	    }"! !
