Class {
	#name : #TestEntitiesOnDisk,
	#superclass : #TestCase,
	#category : #'Kendrick-DSL-Internal'
}

{ #category : #'as yet unclassified' }
TestEntitiesOnDisk >> setUp [

	KendrickInternalDSLEntities clearAll.

	
	

]

{ #category : #'as yet unclassified' }
TestEntitiesOnDisk >> tearDown [

	KendrickInternalDSLEntities clearAll.

	
	

]

{ #category : #'as yet unclassified' }
TestEntitiesOnDisk >> testInfluenza [

	"ensure that you have the folder structure in the same dir as the image and un-comment before running"
	
	"(Visualization withId: 'DiagramVizForInfluenza') open."

	
	

]
